### ISSUE TITLE
"readfile" and "writefile" does not seem to work

### ISSUE THREAD

**Issue by unknown43253252352352** [JezuzLizard/T4SP-Server-Plugin#60]
I am either doing something wrong or the plugins readfile and writefile gsc options does not work.  I get unknown function error when adding the functions to my gsc script. Any help would be appreciated.

Code seems to be there.
![image](https://github.com/JezuzLizard/T4SP-Server-Plugin/assets/148450642/3241634c-b481-4272-ab60-ce5965219e05)

**Comment by ineedbots** [comment]
These were removed; you can use the plutonium's implementation of `filewrite` and `fileread`

**Comment by ineedbots** [comment]
if plutonium's functions dont work well enough for you, I can add a fileio interface to this plugin

**Comment by unknown43253252352352** [comment]
> These were removed; you can use the plutonium's implementation of `filewrite` and `fileread`

Is there any documentation about the plutonium ones? I have never heard of them and have no idea if they work same way as the t6/t5 plugin functions.

By any change you could add the setclantag and setname from t6 gsc utils? I saw some one asking it for t5 utils aswell.

**Comment by unknown43253252352352** [comment]
> if plutonium's functions dont work well enough for you, I can add a fileio interface to this plugin

Small script i tested with and no output was written. I might be doing something wrong ofcourse but that is pretty much t5/t6 plugin handled it. 
```
#include maps\_utility; 
#include common_scripts\utility;
#include maps\_hud_util;
#include maps\_zombiemode_utility;
init()
{
    file = getDvar("fs_homepath") + "\\test.txt";
    filewrite(file, "Hello");
    wait 15;
    get_players()[0] iPrintLn(file);
}   
```

**Comment by ineedbots** [comment]
you dont need to append the fs_homepath for the filename

**Comment by unknown43253252352352** [comment]
> you dont need to append the fs_homepath for the filename

That was to ensure the path but there is no output even without it.

**Comment by unknown43253252352352** [comment]
I have not found anyway to get the plutonium's implementation of filewrite and fileread work. Could anyone help me with that or add the functions to the plugin?

**Comment by ineedbots** [comment]
I will write the new functions here soon

**Comment by ineedbots** [comment]
Latest has the cod4x script functions

https://github.com/callofduty4x/CoD4x_Server/blob/master/scriptdocumentation/script_functions_reference.md#file-operations

**Comment by ineedbots** [comment]
One limitation is that all fileio MUST take place in the `scriptdata` folder

**Comment by ineedbots** [comment]
![image](https://github.com/JezuzLizard/T4SP-Server-Plugin/assets/751729/21f9bafc-13b9-4783-b0a9-866a0431c47b)

**Comment by unknown43253252352352** [comment]
Thank you for adding these functions.

**Comment by anotheruselesaccount** [comment]
This still give unknown function error when adding ```filehandle = fs_fopen("test.txt", "write");```  to my gsc or any other of the functions. 
![image](https://github.com/JezuzLizard/T4SP-Server-Plugin/assets/160650467/b8a8418b-ff9a-4bcd-812f-916e4edb9013)

@ineedbots Am i doing somethign wrong since in console it says plugin loaded but the custom gsc functions does not work when joining server. 

(Issue on my end. server and client tried both load plugin functions )
